Add support for token authentication
salt-extensions/saltext-proxmox pull request #6
Opened 2023-05-05 17:49 UTC by mthibaut

### What does this PR do?

Adds support for giving username/token  instead of a username/password combo to the proxmox API, enhancing security.

### What issues does this PR fix or reference?
Fixes: https://github.com/saltstack/salt/issues/62945
Fixes: https://github.com/salt-extensions/saltext-proxmox/issues/5

2023-05-16 20:19 UTC, nicholasmhughes requested changes

2023-05-16 20:19 UTC, nicholasmhughes commented on src/saltext/proxmox/clouds/proxmox.py
>  def query(conn_type, option, post_data=None):
**issue (blocking):** pre-commit is failing

```suggestion
    authenticated = True


def query(conn_type, option, post_data=None):
```

2023-05-18 15:07 UTC, nicholasmhughes commented
@mthibaut , can we test any of these changes with some basic unit tests?

2023-05-21 20:20 UTC, mthibaut commented
> @mthibaut , can we test any of these changes with some basic unit tests?

@nicholasmhughes Done!

2023-05-25 13:24 UTC, merged